# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##### SITE SETTINGS #####
# The following fields are necessary - replace the values accordingly
title: Harry.Makes.HK
#description: >-
#  Write a description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "/use-namecard" # the subpath of your site, e.g. /blog
url: "https://harrymakes.github.io" # the base hostname & protocol for your site, e.g. http://example.com

##### THEME SETTINGS #####
# [optional] Google analytics ID, e.g. UA-XXXXXXXXX-X
google_analytics:

# [optional] Hex code or CSS color code (defaults to a shade of blue)
accent_color: # light mode accent color
accent_color_dark: # dark mode accent color

# [optional] Dark mode setting (defaults to system)
dark_mode: # system | always | never

# No action needed here, this tells Jekyll to look in the '_sections' directory
collections:
  - sections

# [optional] Social media/contact. Links will appear under the introduction 
#            section with the appropriate logo
github_url: https://github.com/HarryMakes
#stack_overflow_url: https://example.com
#linkedin_url: https://example.com
#facebook_url: https://example.com
#twitter_url: https://example.com
#youtube_url: # you can omit links

email: harry.makes.hk@gmail.com

##### INTRO CONFIGURATION #####
# The following fields configure the introduction section. Markdown is supported
intro_title: |
  **Harry Ho**
  {: .accent-color .jumbo-font}

intro_content: |
  With my ever-burning heart in tech, I have garnered both work and personal achievements in:

  ### ğŸ‘¨â€ğŸ’» **Software Engineering** //

  + low-latency network applications (video/audio streaming, VoIP)
  + web applications & API
  + quick prototyping
  + project management, leadership & ownership
  + modern SDLC practices
  + code safety & security

  ### ğŸ§ **OS Development** //

  + Linux kernel development (C, Rust[ğŸ”—](https://github.com/HarryMakes/rust-out-of-tree-module))
  + socket programming
  + networking stack[ğŸ”—](https://github.com/smoltcp-rs/ENC424J600)
  + distro customisation[ğŸ”—](https://github.com/NixOS/nixpkgs/pulls?q=author%3Aharrymakes)
  + RTOS

  ### ğŸ› ï¸ **Hardware Programming** //

  + object-oriented (C++) safety-first (Rust[ğŸ”—](https://github.com/quartiq/booster)) firmware
  + open-source FPGA logic[ğŸ”—](https://github.com/m-labs/migen)
  + RISC-V SoC footprint[ğŸ”—](https://git.m-labs.hk/M-Labs/HeavyX/src/branch/core_lib)
  + IP libraries[ğŸ”—](https://github.com/m-labs/misoc)
  + PHY/MAC network controllers[*](https://github.com/m-labs/misoc/pull/101)

  {: .secondary-font}

##### BUILD SETTINGS #####
# For gem-based installations, uncomment the following line and comment out 'remote_theme'
# theme: namecard
remote_theme: afterdusk/namecard@v0.1.3
plugins:

# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
